name: Purge cache on markers update

on:
  push:
    branches:
      - master

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get modified markers.js files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'markers.js$' | while read file; do
            echo "https://gitcdn.dinip.pt/Dinip/hermitcraft/master/$file"
          done > modified_files.txt
          if [ -s modified_files.txt ]; then
            echo "FILES_JSON=$(cat modified_files.txt | jq -R . | jq -cs .)" >> $GITHUB_ENV
          else
            echo "FILES_JSON=[]" >> $GITHUB_ENV
          fi

      - name: Files to purge
        run: echo $FILES_JSON | jq .
      
      - name: Purge Cloudflare cache
        if: env.FILES_JSON != '[]'
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -d "{\"files\": $FILES_JSON}" \
            "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_IDENTIFIER }}/purge_cache"
